apiVersion: v1
kind: Service
metadata:
  name: webook-mysql
spec:
  selector:
    app: webook-mysql
  ports:
    - protocol: TCP
      #      你访问的端口
      port: 12216
      targetPort: 3306
  type: LoadBalancer